@Budget.API_HostAddress = http://localhost:5120

### Create a new account
POST {{Budget.API_HostAddress}}/accounts
Content-Type: application/json

{
  "name": "My Savings Account",
  "type": "Savings"
}

###

### Create a new transaction
POST {{Budget.API_HostAddress}}/transactions
Content-Type: application/json

{
  "description": "Grocery Shopping",
  "amount": 75.50,
  "account": { "id": "replace-with-account-id" }
}
###
