
name: Build, Test, and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-publish-release:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '10.x'
      API_PROJECT: 'src/BudgetExperiment.Api/BudgetExperiment.Api.csproj'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore BudgetExperiment.sln

      - name: Build solution
        run: dotnet build BudgetExperiment.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test BudgetExperiment.sln --configuration Release --no-build --logger trx

      - name: Publish API (Linux arm64)
        run: dotnet publish ${{ env.API_PROJECT }} --configuration Release --runtime linux-arm64 --output publish/linux-arm64 --self-contained true

      - name: Publish API (Windows x64)
        run: dotnet publish ${{ env.API_PROJECT }} --configuration Release --runtime win-x64 --output publish/win-x64 --self-contained true

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          prerelease: false
          files: |
            publish/linux-arm64/*
            publish/win-x64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
